name: cache-test

on:
  push:
    branches:
      - main

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: prime-cache-27bf0cc
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-27bf0cc

      - name: show-result
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"

      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install fastapi
